name: 'Update Asana Tasks'
description: 'Manage versions via git tags'
inputs:
  is-prod:
    default: false
  asana-pat:
    required: true
  github-token:
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'