name: 'Update Asana Tasks'
description: 'Manage versions via git tags'
inputs:
  pr-description:
    required: true
  asana-pat:
    required: true
outputs:
  version:
    description: 'new version string'
  tags-to-update-wildcard:
    description: wildcard for querying tags to update
runs:
  using: 'node16'
  main: 'dist/index.js'